sudo: required
dist: trusty

language: cpp
compiler:
  - gcc

env:
  - QTC_SOURCE="$TRAVIS_BUILD_DIR/qt-creator" QTC_VERSION="3.5.1"

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt551-trusty
  - sudo apt-get -qq -y update

install:
  - sudo apt-get -qq -y install qt55base qt55tools qt55svg qt55creator cppcheck
  - git clone https://github.com/qtproject/qt-creator.git
  - pushd qt-creator && git checkout v3.5.1 && popd

script:
  - source /opt/qt55/bin/qt55-env.sh
  - mkdir -p build && cd build
  - >
    qmake ../testplugin.pro -r -spec linux-g++
    CONFIG+=release
    QTC_PLUGIN_DESTDIR="$TRAVIS_BUILD_DIR/build/output"
    LIBS+=-L/opt/qt55/lib/x86_64-linux-gnu/qtcreator
    LIBS+=-L/opt/qt55/lib/x86_64-linux-gnu/qtcreator/plugins
  - make
  - cppcheck `git diff --name-only HEAD^ | grep -i '\.cpp\|\.h'`
